### ISSUE TITLE
[bug] 无法添加cred

### ISSUE THREAD

**Issue by ZGLinus** [qwerdvd/ArknightsUID#4]
运行`skd添加cred ***`后无响应并且无法添加cred
报错日志，已对重要信息打码
```
09-26 11:48:49 [INFO] gsuid_core.handler | [Raw] raw_text=skd添加cred ***, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=***, msg_id=***, user_type=group, group_id=***, user_id=***, user_pm=6, content=[Message(type='text', data='skd添加cred ***')],  
09-26 11:48:49 [INFO] gsuid_core.handler | [Trigger] 消息 「skd添加cred ***」 触发 「prefix」 类型触发器, 关键词: 「skd添加cred」  
09-26 11:48:49 [INFO] gsuid_core.handler | [Command] command=skd添加cred, text= ***
09-26 11:48:49 [DEBUG] ArknightsUID.utils.api.skd.request | https://zonai.skland.com/api/v1/auth/refresh GET {'Host': 'zonai.skland.com', 'platform': '1', 'Origin': 'https://www.skland.com', 'Referer': 'https://www.skland.com/', 'Content-Type': 'application/json', 'User-Agent': 'Skland/1.1.0 (com.hypergryph.skland; build:100100047; Android 33; ) Okhttp/4.11.0', 'vName': '1.1.0', 'vCode': '100100047', 'nId': '1', 'os': '33', 'manufacturer': 'Xiaomi', 'Connection': 'close', 'cred': '***', 'sign_enable': 'false'} None None False 
09-26 11:48:49 [INFO] ArknightsUID.utils.api.skd.request | {'code': 0, 'message': 'OK', 'data': {'token': '***'}} 
Task exception was never retrieved
future: <Task finished name='Task-2500' coro=<send_ark_skd_add_cred_msg() done, defined at /app/gsuid_core/sv.py:30> exception=TypeError('Subscripted generics cannot be used with class and instance checks')>
Traceback (most recent call last):
  File "/app/gsuid_core/sv.py", line 33, in wrapper
    result = await func(bot, event)
  File "/app/gsuid_core/plugins/ArknightsUID/ArknightsUID/arknightsuid_user/__init__.py", line 72, in send_ark_skd_add_cred_msg
    im = await deal_skd_cred(ev.bot_id, ev.text, ev.user_id)
  File "/app/gsuid_core/plugins/ArknightsUID/ArknightsUID/arknightsuid_user/deal_skd_cred.py", line 19, in deal_skd_cred
    token = await ark_skd_api.refresh_token(match.group())
  File "/app/gsuid_core/plugins/ArknightsUID/ArknightsUID/utils/api/skd/request.py", line 202, in refresh_token
    if isinstance(raw_data, Union[int, None]):
  File "/usr/local/lib/python3.9/typing.py", line 720, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/usr/local/lib/python3.9/typing.py", line 723, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

**Comment by qwerdvd** [comment]
fix in 77ea8973c89e02a2091fc67a53dc44e1fc762cb1
